# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      workflow-actions:
        patterns:
          - "*"
    allow:
      - dependency-name: "actions/*"
      - dependency-name: "redhat-actions/*"

  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      # Testcontainers plus the JDBC driver we need for testing
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      # For Hibernate Validator, we will need to update major version manually as needed (but we only use it in tests)
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      # Only patches for Hibernate ORM and Vert.x
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Dockerfiles in tooling/docker/, and database services we use for examples (MySQL and PostgreSQL)
  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "main"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  #################################################################################
  # Duplicate the package-ecosystems for main because we want to target branch 4.2
  # and dependabot doesn't support YAML aliases and anchors at the moment
  #################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.2"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "4.2"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  #################################################################################
  # Duplicate the package-ecosystems for main because we want to target branch 4.1
  # and dependabot doesn't support YAML aliases and anchors at the moment
  #################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.1"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "4.1"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  #################################################################################
  # Duplicate the package-ecosystems for main because we want to target branch 3.3
  # and dependabot doesn't support YAML aliases and anchors at the moment
  #################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "3.3"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "3.3"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  #################################################################################
  # Duplicate the package-ecosystems for main because we want to target branch 3.2
  # and dependabot doesn't support YAML aliases and anchors at the moment
  #################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "3.2"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "3.2"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

#################################################################################
# Duplicate the package-ecosystems for main because we want to target branch 3.1
# and dependabot doesn't support YAML aliases and anchors at the moment
#################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "3.1"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "3.1"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  #################################################################################
  # Duplicate the package-ecosystems for main because we want to target branch 2.4
  # and dependabot doesn't support YAML aliases and anchors at the moment
  #################################################################################
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "2.4"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 20
    groups:
      hibernate-validator:
        patterns:
          - "org.hibernate.validator*"
          - "org.glassfish.expressly*"
      hibernate:
        patterns:
          - "org.hibernate*"
      vertx:
        patterns:
          - "io.vertx*"
      mutiny:
        patterns:
          - "io.smallrye.reactive*"
      # Testcontainers plus the JDBC driver we need for testing
      testcontainers:
        patterns:
          - "org.testcontainers*"
          - "com.ibm.db2*"
          - "com.microsoft.sqlserver*"
          - "org.postgresql*"
          - "con.ongres.scram*"
          - "com.fasterxml.jackson.core*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
    ignore:
      # For Hibernate Validator, we will need to update major version manually as needed (but we only use it in tests)
      - dependency-name: "org.glassfish.expressly*"
        update-types: ["version-update:semver-major"]
      # Don't upgrade from JUnit 5 to 6
      - dependency-name: "org.junit*"
        update-types: [ "version-update:semver-major" ]
      # Only patches for Hibernate ORM and Vert.x
      - dependency-name: "org.hibernate*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.vertx*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.smallrye.reactive*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  # Dockerfiles in tooling/docker/, and database services we use for examples (MySQL and PostgreSQL)
  - package-ecosystem: "docker"
    directory: "/tooling/docker"
    target-branch: "2.4"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
